"""Repository for B-roll artifacts generated by Leo via Omni Flash."""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
import logging
import os
from typing import Any

from croviq_api.config import get_settings
from croviq_domain.narration import BRollArtifact
from croviq_observability import log_firestore_event

logger = logging.getLogger(__name__)


class BRollRepository(ABC):
    """Abstract interface for persisting BRollArtifacts."""

    @abstractmethod
    async def list_by_production_id(self, production_id: str) -> list[BRollArtifact]:
        pass

    @abstractmethod
    async def save(self, artifact: BRollArtifact) -> BRollArtifact:
        pass


class InMemoryBRollRepository(BRollRepository):
    """In-memory repository for unit tests and local non-cloud execution."""

    def __init__(self) -> None:
        self._artifacts: dict[str, list[BRollArtifact]] = {}

    async def list_by_production_id(self, production_id: str) -> list[BRollArtifact]:
        return list(self._artifacts.get(production_id, []))

    async def save(self, artifact: BRollArtifact) -> BRollArtifact:
        if artifact.production_id not in self._artifacts:
            self._artifacts[artifact.production_id] = []
        self._artifacts[artifact.production_id].append(artifact)
        return artifact


class FirestoreBRollRepository(BRollRepository):
    """Production Firestore repository for B-roll persistence."""

    def __init__(self, project_id: str | None = None) -> None:
        self.project_id = project_id or get_settings().gcp_project_id
        self._db: Any = None

    def _get_db(self) -> Any:
        if self._db is None:
            import firebase_admin
            from firebase_admin import firestore
            try:
                firebase_admin.get_app()
            except ValueError:
                firebase_admin.initialize_app(options={"projectId": self.project_id})
            self._db = firestore.client()
        return self._db

    async def list_by_production_id(self, production_id: str) -> list[BRollArtifact]:
        db = self._get_db()
        coll_ref = db.collection("productions").document(production_id).collection("broll_artifacts")
        docs = coll_ref.stream()
        return [BRollArtifact.model_validate(doc.to_dict()) for doc in docs]

    async def save(self, artifact: BRollArtifact) -> BRollArtifact:
        db = self._get_db()
        doc_ref = db.collection("productions").document(artifact.production_id).collection("broll_artifacts").document(artifact.artifact_id)
        doc_ref.set(artifact.model_dump(mode="json"))
        return artifact


_global_broll_repo: BRollRepository | None = None


def get_default_broll_repository() -> BRollRepository:
    global _global_broll_repo
    if _global_broll_repo is None:
        settings = get_settings()
        if settings.environment == "production" or os.getenv("CROVIQ_ENV") == "production":
            _global_broll_repo = FirestoreBRollRepository(project_id=settings.gcp_project_id)
        else:
            _global_broll_repo = InMemoryBRollRepository()
    return _global_broll_repo


def get_broll_repository() -> BRollRepository:
    return get_default_broll_repository()


def set_broll_repository(repo: BRollRepository | None) -> None:
    global _global_broll_repo
    _global_broll_repo = repo
