"""Canonical domain models for Narration, Studio Voice, and B-roll artifacts."""

from datetime import datetime
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from croviq_domain.validators import validate_timezone_aware


class NarrationSegmentStatus(StrEnum):
    """Status of a narration segment synthesis."""

    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    FAILED = "failed"


class NarrationSegment(BaseModel):
    """Minimal canonical narration segment representation."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    segment_id: str = Field(..., min_length=1, description="Unique segment identifier")
    production_id: str = Field(..., min_length=1, description="Associated production identifier")
    source_start_ms: int = Field(..., ge=0, description="Start timestamp on source timeline in ms")
    source_end_ms: int = Field(..., ge=0, description="End timestamp on source timeline in ms")
    available_duration_ms: int = Field(..., ge=0, description="Strict maximum duration budget in ms")
    original_text: str = Field(..., min_length=1, description="Original spoken transcript text")
    rewritten_text: str = Field(..., min_length=1, description="Leo's editorial rewritten text")
    voice_id: str = Field(..., min_length=1, description="Selected Studio Voice identifier")
    generated_duration_ms: int = Field(default=0, ge=0, description="Actual measured TTS audio duration in ms")
    status: NarrationSegmentStatus = Field(default=NarrationSegmentStatus.PENDING)
    audio_artifact_reference: str | None = Field(default=None, description="GCS object or storage key")
    attempts: int = Field(default=1, ge=1, le=5, description="Number of TTS synthesis/rewrite attempts")
    tempo_adjustment: float = Field(default=1.0, ge=0.9, le=1.1, description="Applied tempo multiplier (max 3-5%)")

    @model_validator(mode="after")
    def validate_budget_and_times(self) -> "NarrationSegment":
        if self.source_end_ms < self.source_start_ms:
            raise ValueError("source_end_ms must be >= source_start_ms")
        expected_window = self.source_end_ms - self.source_start_ms
        if self.available_duration_ms == 0 and expected_window > 0:
            self.available_duration_ms = expected_window
        return self


class StudioVoiceResult(BaseModel):
    """Aggregated Studio Voice generation result for a production."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    production_id: str = Field(..., min_length=1)
    voice_id: str = Field(..., min_length=1)
    narration_mode: str = Field(default="studio_voice")
    segments: list[NarrationSegment] = Field(default_factory=list)
    total_segments: int = Field(default=0, ge=0)
    accepted_segments: int = Field(default=0, ge=0)
    all_within_budget: bool = Field(default=True)
    gcs_bucket: str | None = Field(default=None)
    gcs_object: str | None = Field(default=None)
    status: str = Field(default="completed")
    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)

    @field_validator("created_at", "updated_at")
    @classmethod
    def check_tz(cls, v: datetime) -> datetime:
        return validate_timezone_aware(v)


class BRollArtifactStatus(StrEnum):
    """Lifecycle status of a generated B-roll asset."""

    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    FAILED = "failed"


class BRollArtifact(BaseModel):
    """Minimal canonical B-roll artifact generated by Leo via Omni Flash."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    artifact_id: str = Field(..., min_length=1, description="Unique artifact identifier")
    production_id: str = Field(..., min_length=1, description="Associated production identifier")
    decision_id: str | None = Field(default=None, description="Optional associated editor decision id")
    source_start_ms: int = Field(..., ge=0, description="Start time on source timeline in ms")
    source_end_ms: int = Field(..., ge=0, description="End time on source timeline in ms")
    gcs_bucket: str = Field(..., min_length=1)
    gcs_object: str = Field(..., min_length=1)
    duration_ms: int = Field(..., ge=0, description="Target clip duration in ms (~2000-8000ms)")
    status: BRollArtifactStatus = Field(default=BRollArtifactStatus.ACCEPTED)
    prompt_summary: str = Field(default="", description="Human summary of B-roll visual intent")
    created_at: datetime = Field(...)

    @field_validator("created_at")
    @classmethod
    def check_tz(cls, v: datetime) -> datetime:
        return validate_timezone_aware(v)
